project: 
  type: website

website: 
  page-navigation: true
  title: "SAEL Lab Manual" 
  site-url: "https://sael-swfsc.github.io/SAEL-lab-manual" 
  repo-url: "https://github.com/SAEL-SWFSC/SAEL-lab-manual"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/79/NOAA_logo.svg"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.fisheries.noaa.gov/west-coast/science-data/southwest-acoustic-ecology-lab
        text: "Southwest Acoustic Ecology Lab, SWFSC"
      - icon: github
        href: https://github.com/SAEL-SWFSC
        text: "SAEL Github"

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: content/SharedValues-BestPractices.qmd
        text: Shared Values
      - section: "Lab Management"
        contents:
          - content/Safety-Lab.qmd
          - content/Safety_Lithium-Batteries.qmd
          - content/Inventory.qmd
          - content/ProjectManagement.qmd
          - content/Permits.qmd
          - content/Reporting.qmd
          - content/Data-Archive.qmd
          - content/Metadata-Archive.qmd
      - section: "Hardware Methods"
        contents:
          - content/Hardware_ADRIFT.qmd
          - content/Hardware_Handheld-Hydrophone.qmd
      - href: content/Analysis-Methods.qmd
        text: Analysis Methods
      - href: content/media.qmd
        text: Media
      - section: "Documents"
        contents: 
          - content/Documents_Permit-Numbers.qmd
      - href: content/Ocean-Alert-App.qmd
        text: Ocean Alert App
      - section: "Open Science"
        contents: 
          - content/OpenScience_Getting-Started.qmd
          - content/OpenScience_Stack-Exchange.qmd
          - content/OpenScience_Research-Guide.qmd
          - content/OpenScience_CoWorking.qmd
          - content/OpenScience_Writing-Guide.qmd
          - content/OpenScience_Zotero.qmd
          - content/OpenScience_GithubBook.qmd
      - section: "Intro to Acoustics"
        contents:
          - content/Intro-Acoustics.qmd
          - content/Intro-Pamguard.qmd
          - content/Intro-Pampal.qmd
          - content/Intro-Adrift.qmd
        

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
   
     


filters:
  - include-files.lua
  - quarto

  
