---
title: Acoustic Analysis Software 
---

## PAMGuard

The SAEL Lab uses [PAMGuard](https://www.pamguard.org/) for several analysis processes.

## Matlab

[Matlab](https://www.mathworks.com/help/install/ug/install-products-with-internet-connection.html)

### Triton

[Triton](https://github.com/MarineBioAcousticsRC/Triton)

## Raven

[Raven](https://www.ravensoundsoftware.com/software/raven-pro/)

## Python

Python can be used for soundscape analyses using [PyPAM](https://github.com/lifewatch/pypam) and [PBP](https://github.com/mbari-org/pbp)

## LFDCS

[Low Frequency Detection and Classification System (LFDCS)](https://dcs.whoi.edu/lfdcs_manual/lfdcs_manual.html) is a software built by Dr. Mark Baumgartner at the Woods Hole Oceanographic Institution (WHOI). It was designed for automated detection and classification of low-frequency baleen whale vocalizations in real-time acoustic data. It was recently adapted to a LFDCS Desktop program to process archival data as well.

LFDCS requires an IDL Runtime license. More information on the license and how to purchase it can be found [here](https://docs.google.com/document/d/13kLUZrDIE9lL62hnM-tkICCzyYUa_KCn7shHuO-0Gto/edit?usp=sharing)

The SAEL Lab has begun taking some initial steps to use LFDCS Desktop for our data and develop/contribute to a west coast call library.

More information [here](https://docs.google.com/document/d/13kLUZrDIE9lL62hnM-tkICCzyYUa_KCn7shHuO-0Gto/edit?usp=sharing)
