---
title: Archive Methods
---

## Archive Status

<iframe src="https://docs.google.com/spreadsheets/d/1bNu1GPOmyn3CRZ70Mnq4ZZmH7n7ZwIASIlcZD6zWa-k/edit?usp=sharing;gid=1389628961&amp;single=true&amp;widget=true&amp;headers=false" style="width:950px; height:500px; border: 2px solid black;">

</iframe>

## [Google Cloud](https://sael-swfsc.github.io/SAEL-lab-manual/content/Data-Archive-GCP.html)

Google Cloud is for temporary processing/storing of data for Analysis.

## [NCEI](https://sael-swfsc.github.io/SAEL-lab-manual/content/Data-Archive-NCEI.html)

NCEI hosts a [Passive Acoustic Data Archive](https://www.ncei.noaa.gov/products/passive-acoustic-data), where all ADRIFT, CCES, and PASCAL deployment metadata, raw audio data, and soundscape metrics are publicly available. CalCurCEAS 2024 raw audio data will be accessible in this archive once it has been cleared.

Users can access data through the [interactive map](https://www.ncei.noaa.gov/maps/passive-acoustic-data/) or request data using [Google Cloud Platform](https://console.cloud.google.com/marketplace/details/noaa-public/passive_acoustic_monitoring?pli=1&project=ggn-nmfs-pamdata-prod-1)

## [Tethys](https://sael-swfsc.github.io/SAEL-lab-manual/content/Data-Archive-Tethys.html)

All ADRIFT, PASCAL 2016, CCES 2018, and CalCurCEAS 2024 deployment metadata and detection data are archived locally in our lab’s [Tethys database](https://tethys.sdsu.edu/).

The Tethys database is saved locally on the DON server (Z:/ANALYSIS/Tethys). Tethys has multiple ways to access/visualize the database, but these directions will only include opening the web client interface (main web app and Data Explorer).

## [PACM/Makara](https://sael-swfsc.github.io/SAEL-lab-manual/content/Data-Archive-PACM_Makara.qmd)

All ADRIFT, PASCAL 2016, and CCES 2018 marine mammal detection data are archived and available on the [Passive Acoustic Cetacean Map](https://apps-nefsc.fisheries.noaa.gov/pacm/#/) (PACM). Makara is an updated database and methods will be added here

CalCurCEAS 2024 detection data - work in progress

## [InPort](https://sael-swfsc.github.io/SAEL-lab-manual/content/Data-Archive-InPort.html)

Per Fisheries Information Management and Data Documentation policy and procedural directives, all Fisheries data must be inventoried with complete metadata in [InPort](https://www.fisheries.noaa.gov/inport/), NMFS Enterprise Data Management Program. PAM data is complicated, and there is no standard for posting metadata to InPort. Given that detailed metadata is archived to NCEI, SWFSC will post all data related to PAM Deployments/data collection efforts and ensure there is a link to access additional data/metadata via NCEI and PACM.

## OBIS Seamap

We are no longer storing marine mammal detection data in the OBIS database. OBIS specific processing scripts for beaked whales are available [here](https://github.com/TaikiSan21/PAMpal/blob/735dfec50b3c6feaa8772765d752e8260363a2c5/devel/OBIS_Functions.R).
