---
title: NCEI
---

## NCEI Data Archive

<iframe src="https://www.ncei.noaa.gov/maps/passive-acoustic-data/" style="width:950px; height:500px; border: 2px solid black;">

</iframe>

NCEI hosts a [Passive Acoustic Data Archive](https://www.ncei.noaa.gov/products/passive-acoustic-data), where all raw audio files, deployment metadata, and soundscape metrics are publicly available.

Users can access data through the [interactive map](https://www.ncei.noaa.gov/maps/passive-acoustic-data/) or request data using [Google Cloud Platform](https://console.cloud.google.com/marketplace/details/noaa-public/passive_acoustic_monitoring?pli=1&project=ggn-nmfs-pamdata-prod-1)

## Submitting Data

NCEI has packaging tools to help automate this process. ADRIFT, CCES, and PASCAL data was archived using Passive Packer. NCEI has since released the Passive Acoustic Collection Engine (PACE) that allows for bulk processing and custom translators. PACE has replaced Passive Packer as our packaging tool.

### PACE

Future PAM data (CalCurCEAS 2024, gliders, etc) will be packaged and submitted using NCEI's new [Passive Acoustic Collection Engine (PACE)](https://github.com/CI-CMG/pace). Detailed methods for preparing raw audio data for packaging and archive can be found [here](https://github.com/Kourtney-Burger/NCEI-PACE-Data-Archive).

### Passive Packer

::: callout-note
## These methods are no longer in use and may be outdated. Please use PACE archive methods for future projects
:::

All ADRIFT, CCES, and PASCAL data were packaged using a combination of automated scripts and the NCEI Passive Packer tool. Several automation scripts were used to create Passive Packer ready databases from our deployment details metadata. Detailed methods can be found [here](https://sael-swfsc.github.io/adrift-analysis-methods/content/DataArchive/NCEI.html).
