---
title: Tethys
---

## Accessing Data

All ADRIFT, PASCAL, and CCES deployment metadata and detection data are archived locally in our lab's Tethys database.

The Tethys database is saved locally on the DON server (Z:\ANALYSIS\Tethys). Tethys has multiple ways to access/visualize the database, but these directions will only include opening the web client interface (main web app and Data Explorer).

1.  Open Tethys batch file (Z:\ANALYSIS\Tethys\databases\metadata\\tethys.bat)

    ::: callout-note
    This may take a while to load if you have never accessed this database or if you are accessing it remotely (up to an hour)
    :::

2.  Open Data Explorer batch file (Z:\ANALYSIS\Tethys\DataExplorer\data\_explorer.bat)

3.  Once the tethys.bat file has loaded, you should see a prompt to open the main local website

4.  Open \_\_\_ to access the data explorer

5.  Follow the Tethys documentation for [interacting with the web client](https://tethys.sdsu.edu/distribution/current-docs/WebClient.pdf) and [data explorer](https://tethys.sdsu.edu/distribution/current-docs/DataExplorerManual.pdf)

## Archiving Deployment Metadata

## Archiving Detections

See [Tethys SAEL GitHub repository](https://github.com/asimonis/TethysSAEL) and our [detailed methods](https://sael-swfsc.github.io/adrift-analysis-methods/content/DataArchive/TethysDeployments.html) for more information.
