---
title: InPort
---

## InPort Metadata Archive

### Overview

Per Fisheries Information Management and Data Documentation policy and procedural directives, all Fisheries data must be inventoried with complete metadata in InPort, our official metadata repository. PAM data is complicated, and there is no standard for posting metadata to InPort. Given that detailed metadata is archived to NCEI, SWFSC will post all data related to PAM Deployments/data collection efforts and ensure there is a link to access additional data/metadata via NCEI and PACM.

::: callout-note
## InPort data submission guidelines are currently being updated. New guidance detailing InPort data entries is expected to be released with PARR 2.0
:::

### SAEL Data Status

[ADRIFT InPort Entry](https://www.fisheries.noaa.gov/inport/item/75725) - incomplete

All projects need to be archived individually to InPort - waiting for future PARR and InPort guidance

### Access Metadata

You do not need an account to view metadata on InPort. Open the [InPort home page](https://www.fisheries.noaa.gov/inport/) and enter keywords to search the library

### Submitting Metadata

To submit metadata, you first must contact your center InPort Librarians to get an account set up.

Follow detailed methods [here](https://sael-swfsc.github.io/SAEL-lab-manual/content/Slides/InPortDataArchiveMethods.html#/title-slide) to submit metadata according to InPort expectations

### InPort Resources

[InPort Home Page](https://www.fisheries.noaa.gov/inport/)

[SWFSC Organization Library](https://www.fisheries.noaa.gov/inport/hierarchy/1370)

[Help Page](https://www.fisheries.noaa.gov/inport/help)
