---
title: Media
---

## SoundCloud: Public Sound Archive

Our lab has an internal Sound Media Archive in google drive (see link [here](https://drive.google.com/drive/folders/1QjT2dlLJqxO8SmOAfevDQeIo66QqdQ1u?usp=share_link)) as well as a publicly available sound archive on SoundCloud (see link [here](https://soundcloud.com/southwestacousticecology)).

All sounds saved to our SoundCloud archive are available for use and we encourage use in artistic compositions.

## Internal Media Archive

We have internal archives for sounds, images, and videos on our lab Google Drive (see link [here](https://drive.google.com/drive/folders/1s3oXdWLnbofaL1_IwhBoHBVDTBZx1qtB?usp=sharing)). Please document all submissions according to the instructions posted in their respective folders.

## Web Site

The website for the Southwest Acoustic Ecology Lab [main web page](https://www.fisheries.noaa.gov/west-coast/science-data/southwest-acoustic-ecology-lab) currently includes information about our current research activities. For modifications to the website, contact kourtney.burger@noaa.gov.

## Sound Bytes Blog

Our periodic 'Sound Bytes' blog shares stories about how we develop tools, build partnerships, and make discoveries. We encourage all team. A writing/posting guide is available [here](https://sael-swfsc.github.io/SAEL-lab-manual/supplement/SoundBytesBlog_WritingPostingGuide.pdf), and Contact cory.hom-weaver@noaa.gov for more information.

See link to all blogs [here.](https://www.fisheries.noaa.gov/taxonomy/term/1000356091)
