---
title: Permits & Reporting
---

## NOAA Protected Resources Permit

### Permits Numbers

PR1 Permit #0774-1437 from 4/16/1998 - 6/30/2004\
PR1 Permit #774-1714 from 06/30/2004 - 7/7/2010\
Permit \# 14097 from 07/07/2010-06/30/2016\*\
Permit #19091 from 05/17/2016 -- 04/21/2021\
Permit #22306 04/21/2021 -- 04/30/2026

### Permit Reporting

The Protected Resources permit has standardized submission formats for counting and reporting takes. The following scenarios outline how to prepare our data for submission.

Past submissions can be found [here](https://drive.google.com/drive/folders/1-ozXoHNgrZKfSc49WzvezEUh02rg1tMl?usp=sharing).

#### Ocean Alert Marine Mammal Sightings - ADRIFT CCC 

If marine mammal sightings and takes were recorded using the Ocean Alert/Spotter Pro app, the following methods can be used to summarize the necessary reporting data from the app data.

After downloading sightings data from Ocean Alert ([directions here](https://sael-swfsc.github.io/SAEL-lab-manual/content/Ocean-Alert-App.html)), use the automated R script (found [here](https://github.com/SAEL-SWFSC/SAEL-lab-manual/blob/63ad139ac5c49cc3a80f1ef8a3f3c8bcbc2416ac/Scripts/PR_Takes.R)) to pull the necessary protected resources reporting data from our. This script does not produce the final Take Report needed for this permit. It does return takes per species, which can be added to the final Take Report provided by the permit coordinator. Download the script and follow the directions for each reporting cycle.

#### Large Scale MMTD Cruises

Protected resources takes from large scale marine mammal cruises should be reported in one cruise report by the cruise leader. Work with cruise leaders prior to conducting passive acoustic research activities on marine mammals to establish methods for documenting and reporting takes.

#### Opportunistic Deployment Takes

Any opportunistic deployment takes that are not recorded in the Ocean Alert app or part of a large cruise should be summarized manually and reported for each permit year. Record all takes in field notes and deployment details spreadsheet.

## NOAA Sanctuaries Permit

### Permit Numbers

MULTI-2019-005 from 06/04/2019 - 04/20/2024

### Permit Reporting

An automated script can be found [here](https://github.com/SAEL-SWFSC/SAEL-lab-manual/blob/63ad139ac5c49cc3a80f1ef8a3f3c8bcbc2416ac/Scripts/NMS_Reporting.R) for pulling the necessary Sanctuary reporting data from our [Deployment Details spreadsheet](https://docs.google.com/spreadsheets/d/10bxlwfVOe1LFfj69B_YddxcA0V14m7codYwgD2YncFk/edit#gid=395545420). Download the script and follow the directions for each reporting cycle. Contact Kourtney Burger (kourtney.burger\@noaa.gov) with any questions/concerns.

## Fish & Wildlife Permits

**We are no longer conducting research requiring Fish & Wildlife Permits**

## Navy Agreement

### Reporting

An automated script can be found [here](https://github.com/SAEL-SWFSC/SAEL-lab-manual/blob/main/Scripts/NMFS-Navy_PAM-Deployments.R) for pulling the necessary Navy reporting data from our [Deployment Details spreadsheet](https://docs.google.com/spreadsheets/d/10bxlwfVOe1LFfj69B_YddxcA0V14m7codYwgD2YncFk/edit#gid=395545420). Download the script and follow the directions for each reporting cycle. Contact Kourtney Burger (kourtney.burger\@noaa.gov) with any questions/concerns.
